# Generated by Django 5.1.15 on 2026-03-12 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('free_prompts_used', models.PositiveIntegerField(default=0)),
                ('reward_prompts_used', models.PositiveIntegerField(default=0)),
                ('total_prompts_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'daily usage',
                'verbose_name_plural': 'daily usages',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('consume_prompt', 'Consume Prompt'), ('queue_started', 'Queue Started'), ('queue_finished', 'Queue Finished'), ('prompt_failed', 'Prompt Failed'), ('download_completed', 'Download Completed'), ('run_aborted', 'Run Aborted'), ('reward_granted', 'Reward Granted')], db_index=True, max_length=50)),
                ('prompt_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'usage event',
                'verbose_name_plural': 'usage events',
                'ordering': ['-created_at'],
            },
        ),
    ]
