# Generated by Django 5.1.15 on 2026-05-17 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0004_add_downloads_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='extend_prompts_used',
            field=models.PositiveIntegerField(default=0, help_text='Extended video prompts'),
        ),
    ]
