# Generated by Django 5.1.15 on 2026-05-21 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0005_dailyusage_extend_prompts_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='flow_runs_today',
            field=models.PositiveIntegerField(default=0, help_text='Flow queue runs today'),
        ),
        migrations.AddField(
            model_name='dailyusage',
            name='lite_runs_today',
            field=models.PositiveIntegerField(default=0, help_text='Lite queue runs today'),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(choices=[('consume_prompt', 'Consume Prompt'), ('queue_started', 'Queue Started'), ('queue_finished', 'Queue Finished'), ('prompt_failed', 'Prompt Failed'), ('download_completed', 'Download Completed'), ('run_aborted', 'Run Aborted'), ('reward_granted', 'Reward Granted'), ('queue_run_lite', 'Queue Run (Lite)'), ('queue_run_flow', 'Queue Run (Flow)'), ('queue_run_full', 'Queue Run (Full)')], db_index=True, max_length=50),
        ),
        migrations.CreateModel(
            name='MonthlyUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(db_index=True)),
                ('month', models.PositiveIntegerField(db_index=True, help_text='1-12')),
                ('full_runs_used', models.PositiveIntegerField(default=0, help_text='Full queue runs this month')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'monthly usage',
                'verbose_name_plural': 'monthly usages',
                'ordering': ['-year', '-month'],
                'unique_together': {('user', 'year', 'month')},
            },
        ),
    ]
