# Generated by Django 5.1.15 on 2026-03-12 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10)),
                ('is_pro_active', models.BooleanField(default=False)),
                ('fair_use_flag', models.BooleanField(default=False)),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('whop_user_id', models.CharField(blank=True, max_length=128, null=True)),
                ('whop_membership_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
