# Generated by Django 5.1.15 on 2026-03-12 11:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewardCreditLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Positive = grant, negative = consumption')),
                ('source', models.CharField(db_index=True, help_text='e.g. rewarded_ad, manual_grant, prompt_consumption', max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='Idempotency key — prevents duplicate grants', max_length=128, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reward credit entry',
                'verbose_name_plural': 'reward credit entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
