# Generated by Django 5.1.15 on 2026-05-14 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_reviewrewardclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrewardclaim',
            name='reviewer_name',
            field=models.CharField(blank=True, help_text='Chrome Web Store display name provided by user for verification', max_length=100),
        ),
    ]
